### PR TITLE
fix: cache timeouts

### LINKED ISSUE #155: Flag evaluation timeout is broken in the react integration.
Flag evaluation timeouts aren't stored in the local cache, so when a suspending flag evaluation times out it will re-render and just start a new timeout.

## Expected Behavior

Suspend is resolved on timeout and default values shown.

## Current Behavior

Suspend fallback is shown indefinitely as long as requests keep timing out. 

## Possible Solution

Store timed out flag resolutions in the client cache.

### PR DESCRIPTION
**Pull request by andreas-karlsson**
## Hi There, I just made a Pull Request!

Move resolve timeout functionality to the FlagResolverClient, which in turn fixes two problems:

1. Failing requests aren't any longer retried indefinitely.
2. Failed requests are now cached so that they also work with Reac Suspense.

Fixes #155

### CODE REVIEW

File: packages/sdk/src/FlagResolverClient.ts [hunk 1]
```diff
@@ -266,9 +302,13 @@ export function withRequestLogic(fetchImplementation: (request: Request) => Prom
...
 
-function patch<T, K extends keyof T>(obj: T, key: K, fn: (original: T[K]) => T[K]): T {
-  // @ts-ignore
-  const original = obj[key].bind(obj);
-  obj[key] = fn(original);
-  return obj;
+function withTimeout(signal: AbortSignal, timeout: number, reason?: any): AbortSignal {
+  const controller = new AbortController();
+  const timeoutId: NodeJS.Timeout | number = setTimeout(() => controller.abort(reason), timeout);
+  if (typeof timeoutId === 'object') timeoutId.unref();
```
Comment (nicklasl) [inline packages/sdk/src/FlagResolverClient.ts:308]: leave comment about this?

File: packages/sdk/src/Confidence.ts [hunk 2]
```diff
@@ -269,10 +265,11 @@ export class Confidence implements EventSender, Trackable, FlagResolver {
       fetchImplementation,
       sdk,
       environment,
+      resolveTimeout: timeout,
       region,
     });
     if (environment === 'client') {
-      flagResolverClient = new CachingFlagResolverClient(flagResolverClient, 30_000);
+      flagResolverClient = new CachingFlagResolverClient(flagResolverClient, 3600_000);
```
Comment (nicklasl) [inline packages/sdk/src/Confidence.ts:272]:
```suggestion
      flagResolverClient = new CachingFlagResolverClient(flagResolverClient, 30_000);
```

File: packages/react/src/index.tsx [hunk 3]
```diff
@@ -39,8 +38,15 @@ export class ConfidenceReact implements EventSender, Trackable, FlagResolver {
...
-  get state(): State {
-    return this.delegate.flagState;
+  get contextState(): string {
+    const state = this.delegate.flagState;
+    switch (state) {
+      case 'READY':
+      case 'ERROR':
+        return state + Value.serialize(this.delegate.getContext());
+      default:
+        return '';
```
Comment (nicklasl) [inline packages/react/src/index.tsx:48]: maybe not safe to return `''` here?

File: examples/react18/src/index.tsx [hunk 4]
```diff
@@ -4,8 +4,9 @@ import App from './App';
...
-  <React.StrictMode>
-    <App />
-  </React.StrictMode>,
-);
+// root.render(
+//   <React.StrictMode>
+//     <App />
+//   </React.StrictMode>,
+// );
+root.render(<App />);
```
Comment (nicklasl) [inline examples/react18/src/index.tsx:12]: restore

File: examples/react18/src/App.tsx [hunk 5]
```diff
@@ -1,32 +1,109 @@
...
+  timeout: 5000,
   logger: console,
+  fetchImplementation: (req: Request) => {
+    console.log('request', req.url);
+    return state.failRequests ? Promise.resolve(new Response(null, { status: 500 })) : fetch(req);
+  },
 });
 
-confidence.track(pageViews());
+// confidence.track(pageViews());
```
Comment (nicklasl) [inline examples/react18/src/App.tsx:31]: clean up (remove the tracking)

File: packages/sdk/src/FlagResolverClient.ts [hunk 6]
```diff
@@ -108,11 +122,22 @@ export class FetchingFlagResolverClient implements FlagResolverClient {
...
+        new ResolveError('TIMEOUT', 'Resolve timeout'),
+      );
+      return this.resolveFlagsJson(request, signalWithTimeout)
+        .then(response => FlagResolution.ready(context, response, this.createApplier(response.resolveToken)))
+        .catch(error => {
+          if (error instanceof ResolveError) {
+            return FlagResolution.failed(context, error.code, error.message);
+          }
+          throw error;
+          // return FlagResolution.failed(context, 'GENERAL', error.message);
```
Comment (andreas-karlsson) [inline packages/sdk/src/FlagResolverClient.ts:138]: Remove.

**Review by nicklasl — APPROVED** [review]
